server:
  port: 8080
  servlet:
    context-path: /santaweek
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://tjzjqwdlrhjopx:6749dbea7617a7fe26009f7d019a477dcf9a7f65b3c75ff58678ff8206f8cfe6@ec2-54-163-97-228.compute-1.amazonaws.com:5432/detahnb3krqbr
    username: tjzjqwdlrhjopx
    password: 6749dbea7617a7fe26009f7d019a477dcf9a7f65b3c75ff58678ff8206f8cfe6

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto Criado para o Bootcamp DIO - Santander